version: 2.1

jobs: 
  build:
    docker: 
      - image: hashicorp/terraform   # this terraform image to run our project 
    steps: 
      - checkout 
      - run:
          name: "init"
          command: terraform init 
      - run:
          name: "plan"
          command: terraform plan
      
  build2:
    docker: 
      - image: hashicorp/terraform   # this terraform image to run our project 
    steps:
      - checkout 
      - run:
          name: "init"
          command: terraform init 
      - run:
          name: "plan"
          command: terraform plan
      - run:
          name: "apply"
          command: terraform apply --auto-approve #we have to 
      

           
workflows: 
  build:
    jobs:
      - build:
          context: dev-server-cred
      - hold:
          type: approval 
          requires:
            - build
      - build2:
          context: prod-server-cred
          requires: 
            - hold
